# Generated by Django 5.0.6 on 2024-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.CharField(max_length=25),
        ),
    ]
